UBUNTU: SAUCE: client/shared/logging_manager.py: take more unused args for _logging_manager_aware_logger__find_caller
In logging in python 3.8 will pass 3 positional arguments to
_logging_manager_aware_logger__find_caller, thus it will fail with:
Traceback (most recent call last):
  File /home/ubuntu/autotest/client/job.py, line 1268, in runjob
    myjob = job(control=control, drop_caches=drop_caches, options=options)
  File /home/ubuntu/autotest/client/job.py, line 120, in __init__
    self._pre_record_init(control, options)
  File /home/ubuntu/autotest/client/job.py, line 188, in _pre_record_init
    logging.info('Writing results to %s', self.resultdir)
  File /usr/lib/python3.8/logging/__init__.py, line 2070, in info
    root.info(msg, *args, **kwargs)
  File /usr/lib/python3.8/logging/__init__.py, line 1434, in info
    self._log(INFO, msg, args, **kwargs)
  File /usr/lib/python3.8/logging/__init__.py, line 1565, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: _logging_manager_aware_logger__find_caller() takes 2 positional arguments but 3 were given

Since we don't need to use the arguments here, use *args to catch
additional arguments and keep the compatibility.

Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>