Revert "UBUNTU: SAUCE: fix missing setup on second run"
This reverts commit f6e444df45f45fccd3b18f098233e5c4fabe1153.

The change looks incorrect because it makes the setup() basically the
same as initialize() callback.  Instead each test should be fixed so on
next runs it will work with setup() being called only once.

This change also breaks several tests which do not clean after setup()
or are not prepared for resources already prepared, like "git clone".
For example ubuntu_ltp_syscalls:

    INFO | START	----	----	timestamp=1623064688	localtime=Jun 07 11:18:08
    DEBUG| Persistent state client._record_indent now set to 1
    DEBUG| Test has timeout: 1800 sec.
    INFO | 	START	ubuntu_ltp_syscalls.setup	ubuntu_ltp_syscalls.setup	timestamp=1623064688	timeout=1800	localtime=Jun 07
    ...
    DEBUG| Running 'git clone https://github.com/linux-test-project/ltp.git'
    ERROR| [stderr] fatal: destination path 'ltp' already exists and is not an empty directory.
    ERROR| Exception escaping from test:
    Traceback (most recent call last):
      File "/home/ubuntu/autotest/client/shared/test.py", line 387, in _exec
        *p_args, **p_dargs)
      File "/home/ubuntu/autotest/client/shared/utils.py", line 868, in update_version
        install(*args, **dargs)
      File "/home/ubuntu/autotest/client/tests/ubuntu_ltp_syscalls/ubuntu_ltp_syscalls.py", line 85, in setup
        self.results = utils.system_output(cmd, retain_output=True)
      File "/home/ubuntu/autotest/client/shared/utils.py", line 1271, in system_output
        verbose=verbose, args=args).stdout
      File "/home/ubuntu/autotest/client/shared/utils.py", line 922, in run
        "Command returned non-zero exit status")
    CmdError: Command <git clone https://github.com/linux-test-project/ltp.git> failed, rc=128, Command returned non-zero exit status
    * Command:
        git clone https://github.com/linux-test-project/ltp.git

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@canonical.com>
Acked-by: Po-Hsu Lin <po-hsu.lin@canonical.com>
Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>